apiVersion: v1
kind: Service
metadata:
  name: secret-service
  namespace: Go-Applications
spec:
  type: LoadBalancer
  selector:
    app: Go app Go
  ports:
  - port: 8433
    targetPort: 8433
    name: https
  - port: 8080
    targetPort: 8080
    name: http
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127